---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: ec2
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:

  - name: test-aws-centos7-zookeeper
    image: ami-9887c6e7
    platform: centos7
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family
      - zookeeper
      - package_install

  - name: test-aws-centos8-zookeeper-current
    image: ami-0ed2ad9dc845b42b6
    platform: centos8
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family
      - zookeeper

  - name: test-aws-Amazon2-zookeeper
    image: ami-0b898040803850657
    platform: amazon2
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: ec2-user
    groups:
      - rhel_family
      - zookeeper

  - name: test-aws-ubuntu18-zookeeper
    image: ami-012fd5eb46f56731f
    platform: ubuntu18
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    security_group_name:
      - default
    spot_price: 0.04
    wait_timeout: 1800
    ssh_user: ubuntu
    groups:
      - debian_family
      - zookeeper
      - package_install

  - name: test-aws-Debian9-zookeeper
    image: ami-003f19e0e687de1cd
    platform: debian9
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: admin
    groups:
      - debian_family
      - zookeeper
      - zookeeper_3_5

provisioner:
  name: ansible
  log: false
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
  inventory:
    group_vars:
      package_install:
        zk_tarball_installation: false
      zookeeper_3_5:
        zk_version: 3.5.5
      windows:
        ansible_connection: winrm
        ansible_password: "{{ lookup('env', 'WINRM_ADMIN_PWD') | default('M0leCule123!', true) }}"
        ansible_winrm_transport: credssp
        ansible_winrm_server_cert_validation: ignore
      chocolatey:
        zk_tarball_installation:  false
      tarball:
        zk_tarball_installation:  true
  playbooks:
    create: ../resources/provisioning/AWS/create.yml
    prepare: ../resources/prepare.yml
    destroy: ../resources/provisioning/AWS/destroy.yml
    verify: ../resources/tests/verify.yml
  lint:
    name: ansible-lint
scenario:
  name: cloud-aws-direct
verifier:
  name: ansible
  lint:
    name: ansible-lint
