# Box / OS
VAGRANT_BOX = 'ubuntu/trusty64'

# Memorable name for your
VM_NAME = 'savemoney-development'

# VM User — 'vagrant' by default
VM_USER = 'vagrant'

Vagrant.configure("2") do |config|
  # Vagrant box from Hashicorp
  config.vm.box = VAGRANT_BOX

  # Actual machine name
  config.vm.hostname = VM_NAME

  config.vm.provider "virtualbox" do |v|
    v.name = VM_NAME
    v.memory = 6048
    v.gui = true
  end
  #DHCP — comment this out if planning on using NAT instead
  config.vm.network "private_network", type: "dhcp"
  # # Port forwarding — uncomment this to use NAT instead of DHCP
  # config.vm.network "forwarded_port", guest: 80, host: VM_PORT

  # Sync folder
  # config.vm.synced_folder HOST_PATH, GUEST_PATH

  # Disable default Vagrant folder, use a unique path per project
  #  config.vm.synced_folder '.', '/home/'+VM_USER+'', disabled: true
    # Install Git, Node.js 6.x.x, Latest npm
    config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get install xfce4
    sudo startxfce4&
    apt-get update
    apt-get install -y git
    apt-get install -y nodejs
    nodejs --version
    apt-get install -y build-essential
    npm install -g npm
    apt-get install docker.io
    curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
    docker-compose --version
    apt-get update
    apt-get upgrade -y
    apt-get autoremove -y
  SHELL
  
end