---
- name: Load a system variables file based on distribution or OS family
  include_vars: '{{ distribution }}'
  with_first_found:
    - '{{ ansible_system }}.yml'
    - default.yml
  loop_control:
    loop_var: distribution

- name: Choose platform based task
  include_tasks: '{{ platform }}'
  with_first_found:
    - '{{ ansible_system }}/system.yml'
    - not-supported.yml
  loop_control:
    loop_var: platform
