---
- name: Zookeeper Installation
  include_tasks: '{{ zk_install_type }}.yml'

- name: Start and Enable zookeeper service
  service:
    name: '{{ zk_service_name }}'
    enabled: '{{ zk_service_autostart | bool }}'
    state: started
  become: true
  when:
    - zk_service_start | bool
